name: Chrome Extension CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate manifest.json
      run: |
        # Check if manifest.json exists and is valid JSON
        if [ ! -f "manifest.json" ]; then
          echo "❌ manifest.json not found"
          exit 1
        fi
        
        # Validate JSON syntax
        python3 -m json.tool manifest.json > /dev/null
        if [ $? -eq 0 ]; then
          echo "✅ manifest.json is valid JSON"
        else
          echo "❌ manifest.json contains invalid JSON"
          exit 1
        fi
        
        # Check required fields
        python3 -c "
        import json
        with open('manifest.json', 'r') as f:
            manifest = json.load(f)
        
        required_fields = ['manifest_version', 'name', 'version', 'permissions', 'action']
        missing_fields = [field for field in required_fields if field not in manifest]
        
        if missing_fields:
            print(f'❌ Missing required fields: {missing_fields}')
            exit(1)
        else:
            print('✅ All required fields present')
        "
    
    - name: Check file structure
      run: |
        echo "Checking required files and directories..."
        
        # Check required directories
        required_dirs=("background" "content" "popup" "icons")
        for dir in "${required_dirs[@]}"; do
          if [ -d "$dir" ]; then
            echo "✅ Directory $dir exists"
          else
            echo "❌ Directory $dir missing"
            exit 1
          fi
        done
        
        # Check required files
        required_files=("background/service-worker.js" "content/content.js" "popup/popup.html" "popup/popup.js" "popup/popup.css")
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ File $file exists"
          else
            echo "❌ File $file missing"
            exit 1
          fi
        done
        
        # Check icon files
        icon_files=("icons/icon16.png" "icons/icon48.png" "icons/icon128.png")
        for file in "${icon_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ Icon $file exists"
          else
            echo "❌ Icon $file missing"
            exit 1
          fi
        done
    
    - name: Validate JavaScript syntax
      run: |
        echo "Checking JavaScript syntax..."
        
        # Find all JS files
        find . -name "*.js" -not -path "./node_modules/*" | while read -r file; do
          echo "Checking $file..."
          node -c "$file"
          if [ $? -eq 0 ]; then
            echo "✅ $file syntax is valid"
          else
            echo "❌ $file has syntax errors"
            exit 1
          fi
        done
    
    - name: Check for common issues
      run: |
        echo "Checking for common Chrome extension issues..."
        
        # Check for console.log statements (optional - remove if you want to keep them)
        console_logs=$(grep -r "console\.log" --include="*.js" . | wc -l)
        if [ $console_logs -gt 0 ]; then
          echo "⚠️  Found $console_logs console.log statements (consider removing for production)"
        fi
        
        # Check for TODO comments
        todos=$(grep -r "TODO\|FIXME\|HACK" --include="*.js" . | wc -l)
        if [ $todos -gt 0 ]; then
          echo "⚠️  Found $todos TODO/FIXME/HACK comments"
        fi
        
        echo "✅ Basic validation complete"
    
    - name: Package extension
      run: |
        echo "Creating extension package..."
        zip -r cornerstone-lms-tools.zip . -x '*.git*' 'node_modules/*' '*.zip' '*.md' 'package*.json' '.github/*'
        
        if [ -f "cornerstone-lms-tools.zip" ]; then
          echo "✅ Extension packaged successfully"
          ls -lh cornerstone-lms-tools.zip
        else
          echo "❌ Failed to create extension package"
          exit 1
        fi
    
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: cornerstone-lms-tools-extension
        path: cornerstone-lms-tools.zip
        retention-days: 30
